#!/usr/bin/env python
"""Verify a built wheel/sdist actually carries everything a user needs.

`pip install xorcise` must give a working `xorcise up` — which means the wheel has to carry
three things that are NOT plain Python source and are therefore easy to lose silently:

1. the Next.js static export (`core/frontend/_static/**`) — VCS-ignored, force-included via
   `[tool.hatch.build.targets.wheel].artifacts` and regenerated by `hatch_build.py`. A Node-less
   build machine degrades to "ship the existing export", so a stale/empty `_static` is a real
   failure mode that no Python test would catch;
2. `ROLE_MANIFEST.toml` — force-included, read at runtime to resolve roles;
3. the mission-base build context — force-included so the runner can build the base image
   from a real install (there is no published registry).

Losing any of these produces a wheel that imports fine, passes the test suite, and then fails
in a user's hands. This script is the gate; CI (`build-dist`) and `release.yml` both run it, so
the release path cannot be validated more loosely than a pull request.

Usage:  python scripts/check_wheel_contents.py [DIST_DIR]   (default: dist/)
Exit:   0 = all required content present; 1 = something is missing.
"""

from __future__ import annotations

import sys
import tarfile
import zipfile
from pathlib import Path

# Paths are wheel-internal (i.e. relative to the wheel root, which contains `xorcise/`).
REQUIRED_EXACT = (
    "xorcise/__init__.py",
    "xorcise/ROLE_MANIFEST.toml",
    "xorcise/core/frontend/_static/index.html",
    "xorcise/core/runner/docker/_mission_base/Dockerfile",
    "xorcise/core/runner/docker/_mission_base/entrypoint.sh",
)

# (label, prefix, minimum number of members) — guards against an empty-but-present directory.
REQUIRED_PREFIXES = (
    ("Next.js static export", "xorcise/core/frontend/_static/_next/", 1),
    ("Alembic migrations", "xorcise/core/db/migrations/versions/", 1),
)


def _fail(msg: str) -> None:
    print(f"WHEEL-GUARD: {msg}")


def check_wheel(wheel: Path) -> list[str]:
    errors: list[str] = []
    with zipfile.ZipFile(wheel) as zf:
        names = set(zf.namelist())

    for required in REQUIRED_EXACT:
        if required not in names:
            errors.append(f"missing required file: {required}")

    for label, prefix, minimum in REQUIRED_PREFIXES:
        # Directory entries themselves are not counted — only real files under the prefix.
        found = [n for n in names if n.startswith(prefix) and not n.endswith("/")]
        if len(found) < minimum:
            errors.append(
                f"{label}: expected >= {minimum} file(s) under {prefix}, found {len(found)}"
            )

    # A wheel with at most one _static file means the frontend build silently degraded
    # (npm missing / build skipped). Catch that specifically: it is the single most likely
    # packaging regression and the error above ("_next/") would be cryptic alone.
    static = [
        n for n in names if n.startswith("xorcise/core/frontend/_static/") and not n.endswith("/")
    ]
    if len(static) <= 1:
        errors.append(
            "frontend export is incomplete "
            f"({len(static)} file(s) under _static/) — the Next.js build did not run. "
            "Build the wheel on a machine with Node/npm available."
        )
    return errors


def check_sdist(sdist: Path) -> list[str]:
    """The sdist must at least carry the build inputs; `_static` is a build artifact."""
    errors: list[str] = []
    with tarfile.open(sdist) as tf:
        names = tf.getnames()
    # Strip the leading `xorcise-<version>/` component that sdists always carry.
    stripped = {n.split("/", 1)[1] for n in names if "/" in n}
    for required in ("pyproject.toml", "hatch_build.py", "ROLE_MANIFEST.toml", "README.md"):
        if required not in stripped:
            errors.append(f"sdist missing required file: {required}")
    return errors


def main(argv: list[str]) -> int:
    dist = Path(argv[1] if len(argv) > 1 else "dist")
    if not dist.is_dir():
        _fail(f"dist directory not found: {dist}")
        return 1

    wheels = sorted(dist.glob("*.whl"))
    sdists = sorted(dist.glob("*.tar.gz"))
    errors: list[str] = []

    if len(wheels) != 1:
        errors.append(
            f"expected exactly 1 wheel in {dist}, found {len(wheels)}: {[w.name for w in wheels]}"
        )
    if len(sdists) != 1:
        errors.append(
            f"expected exactly 1 sdist in {dist}, found {len(sdists)}: {[s.name for s in sdists]}"
        )
    if errors:
        for e in errors:
            _fail(e)
        return 1

    wheel, sdist = wheels[0], sdists[0]
    print(f"wheel: {wheel.name}")
    print(f"sdist: {sdist.name}")

    errors.extend(check_wheel(wheel))
    errors.extend(check_sdist(sdist))

    if errors:
        for e in errors:
            _fail(e)
        return 1

    print(
        "wheel contents OK — frontend export, role manifest, migrations and "
        "mission-base context all present."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
